development:
  adapter: mysql2
  database: brooch_development
  username: root
  password:
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

test:
  adapter: mysql2
  database: brooch_test
  username: root
  password:
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5

production:
  adapter: mysql2
  database: brooch
  username: root
  password:
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5
